### ISSUE TITLE
Problem with snapping without EnableSnapping

### ISSUE THREAD

**Issue by Kaitoukid93** [mircea21S/RichCanvas#23] opened 2023-05-22 10:10 UTC
Thanks for creating awesome library
I'm not sure if the title correct but I don't know how to describe this
I have a RichCanvas with default properties, but the dragging beavior is not what I expected (as I experienced  in demo App)
The `Container `and `Drag Selection Rectangle` only show their position snap to 1 pixel, even I change `GridSpacing ` to bigger or smaller number, the update tick remain the same as 1 unit 
` <richcanvas:RichItemsControl
            EnableGrid="true"
            GridSpacing="1"
            MaxScale="100"
            MinScale="0.1"
            ></richcanvas:RichItemsControl>`

https://github.com/mircea21S/RichCanvas/assets/40384831/42c2e63f-4f20-4400-a6e0-e17826c11b4a

The only thing that I changed is AttachedAdorner and it's long ago( I want to remove Resize adorner thumb for some reason I didn't even remember 😅 )

**Comment by Kaitoukid93** [comment] 2023-05-22 17:11
I found the cause of this!
I don't know for what reason, if I using `Window `instead of `hc:Window`(from HandyControls), the problem is no longer exists

**Comment by mircea21S** [comment] 2023-05-26 10:22
Hi,

Thank you for your appreciation and I am glad you've found a solution in time. Just so you know, I've managed to reproduce your issue with the `Window` from HandyControls. For the moment, I won't be looking into this as I am working on other stuff, but I'll definitely try to fix it later.

I'll reopen the issue for tracking.

Thanks!

**Comment by Kaitoukid93** [comment] 2023-05-27 18:16
Sorry for not updating this, I have a feeling this is neither your library nor HandyControl's fault since I have this problem.
Indeed, this cause by HandyControl Enable 'UseLayoutRounding' by default with their custom window to avoid blurry text
So I just need to set it to 'false' in richCanvas:
Thanks!

**Comment by mircea21S** [comment] 2023-06-02 19:12
Oh! Okay, that sounds like a fix and a possible root cause, if this works for you I will close the issue and if anything appears or I will find anything we can reopen it.
Thanks!

**Closed by mircea21S** 2023-06-02 19:12 UTC
Labels: investigation
